---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 8/20/2023 12:56 AM
---
require ("util")
local sounds = require("__base__.prototypes.entity.sounds")
local hit_effects = require ("__base__.prototypes.entity.hit-effects")

local Sprites = require('__stdlib__/stdlib/data/modules/sprites')
local TerranSound = require('__erm_terran_hd_assets__/sound')
local AnimationDB = require('__erm_terran_hd_assets__/animation_db')
local ERMPlayerUnitHelper = require('__enemyracemanager__/lib/rig/player_unit_helper')

local collision_box = { { -2, -1.5 }, { 2, 1.5 } }
local selection_box = { { -2, -1.5 }, { 2, 1.5 } }

local min_range = 16
local attack_range = math.ceil(ERMPlayerUnitHelper.get_attack_range(1.35, min_range))
local prepare_range = attack_range + 4

local east_animation_folding = AnimationDB.get_layered_animations('buildings', 'siege_tank_siege_mode_east', 'folding')
east_animation_folding = AnimationDB.apply_runtime_tint(east_animation_folding, true)
east_animation_folding = AnimationDB.shift(east_animation_folding, {-0.25, -1.4})

local east_animation_folded = AnimationDB.get_layered_animations('buildings', 'siege_tank_siege_mode_east', 'folded')
east_animation_folded = AnimationDB.apply_runtime_tint(east_animation_folded, true)
east_animation_folded = AnimationDB.shift(east_animation_folded, {-0.25, -1.4})

local east_animation_preparing = AnimationDB.get_layered_animations('buildings', 'siege_tank_siege_mode_east', 'preparing')
east_animation_preparing = AnimationDB.apply_runtime_tint(east_animation_preparing, true)
east_animation_preparing = AnimationDB.shift(east_animation_preparing, {-0.25, -1.4})

local east_animation_prepared = AnimationDB.get_layered_animations('buildings', 'siege_tank_siege_mode_east', 'prepared')
east_animation_prepared = AnimationDB.apply_runtime_tint(east_animation_prepared, true)
east_animation_prepared = AnimationDB.shift(east_animation_prepared, {-0.25, -1.4})

local east_animation_attack = AnimationDB.get_layered_animations('buildings', 'siege_tank_siege_mode_east', 'attack')
east_animation_attack = AnimationDB.apply_runtime_tint(east_animation_attack, true)
east_animation_attack = AnimationDB.shift(east_animation_attack, {-0.25, -1.4})

local west_animation_folding = AnimationDB.get_layered_animations('buildings', 'siege_tank_siege_mode_west', 'folding')
west_animation_folding = AnimationDB.apply_runtime_tint(west_animation_folding, true)
west_animation_folding = AnimationDB.shift(west_animation_folding, {0.25, -1.4})

local west_animation_folded = AnimationDB.get_layered_animations('buildings', 'siege_tank_siege_mode_west', 'folded')
west_animation_folded = AnimationDB.apply_runtime_tint(west_animation_folded, true)
west_animation_folded = AnimationDB.shift(west_animation_folded, {0.25, -1.4})

local west_animation_preparing = AnimationDB.get_layered_animations('buildings', 'siege_tank_siege_mode_west', 'preparing')
west_animation_preparing = AnimationDB.apply_runtime_tint(west_animation_preparing, true)
west_animation_preparing = AnimationDB.shift(west_animation_preparing, {0.25, -1.4})

local west_animation_prepared = AnimationDB.get_layered_animations('buildings', 'siege_tank_siege_mode_west', 'prepared')
west_animation_prepared = AnimationDB.apply_runtime_tint(west_animation_prepared, true)
west_animation_prepared = AnimationDB.shift(west_animation_prepared, {0.25, -1.4})

local west_animation_attack = AnimationDB.get_layered_animations('buildings', 'siege_tank_siege_mode_west', 'attack')
west_animation_attack = AnimationDB.apply_runtime_tint(west_animation_attack, true)
west_animation_attack = AnimationDB.shift(west_animation_attack, {0.25, -1.4})

data:extend({
    {
        type = "ammo-turret",
        name = MOD_NAME.."/siege-tank-turret",
        icons = {
            {
                icon = "__erm_terran_hd_assets__/graphics/entity/icons/buildings/siege_tank_siege_mode256.png",
                icon_size = 256,
            },
        },
        resistances =
        {
            { type = "poison", percent = 50 },
            { type = "physical", percent = 50 },
            { type = "fire", percent = 50 },
            { type = "explosion", percent = 50},
            { type = "laser", percent = 50 },
            { type = "electric", percent = 50 },
            { type = "cold", percent = 50},
            { type = "impact", percent = 90, decrease = 50 },
        },
        flags = {"placeable-player", "player-creation"},
        max_health = 2400,
        dying_explosion = MOD_NAME.."/building-large-explosion",
        minable = {mining_time = 2, result = MOD_NAME .. '/siege-tank-turret'},
        repair_speed_modifier = 0.33,
        collision_box = collision_box,
        selection_box = selection_box,
        damaged_trigger_effect = hit_effects.entity(),
        rotation_speed = 0.015,
        preparing_speed = 0.08,
        folding_speed = 0.08,
        inventory_size = 1,
        automated_ammo_count = 5,
        attacking_speed = 0.5,
        alert_when_attacking = false,
        open_sound = sounds.machine_open,
        close_sound = sounds.machine_close,
        base_picture = {
            north = east_animation_folded,
            east = east_animation_folded,
            south = west_animation_folded,
            west = west_animation_folded,
        },
        turret_base_has_direction = true,
        vehicle_impact_sound = sounds.generic_impact,
        prepare_range = prepare_range,
        folded_animation = {
            north = east_animation_folded,
            east = east_animation_folded,
            south = west_animation_folded,
            west = west_animation_folded,
        },
        folding_animation = {
            north = east_animation_folding,
            east = east_animation_folding,
            south = west_animation_folding,
            west = west_animation_folding,
        },
        prepared_animation = {
            north = east_animation_prepared,
            east = east_animation_prepared,
            south = west_animation_prepared,
            west = west_animation_prepared,
        },
        preparing_animation = {
            north = east_animation_preparing,
            east = east_animation_preparing,
            south = west_animation_preparing,
            west = west_animation_preparing,
        },
        attacking_animation = {
            north = east_animation_attack,
            east = east_animation_attack,
            south = west_animation_attack,
            west = west_animation_attack,
        },
        attack_parameters =
        {
            type = "projectile",
            ammo_category = "cannon-shell",
            cooldown = 300,
            cooldown_deviation = 0.2,
            projectile_creation_distance = 1.39375,
            projectile_center = {0, -0.0875}, -- same as gun_turret_attack shift
            range = attack_range,
            min_range = min_range,
            health_penalty = 15,
            rotate_penalty = 15,
            sound = TerranSound.shockbomb(0.75, 1)
        },
        call_for_help_radius = 0,
    },
})