---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 12/22/2020 7:15 PM
---

-- Globals within the mod
MOD_NAME = 'erm_terran'

DEBUG_MODE = false

SELF_DESTRUCT_ATTACK = 'emtrn-slfd'
TIME_TO_LIVE_DIED = 'emtrn-ttld'
TIME_TO_LIVE_CREATED = 'emtrn-ttlc'

GHOST_ATOMIC_SEQUENCE = 'emtrn-ghnk'
CANCEL_GHOST_ATOMIC_SEQUENCE = 'emtrn-cgnk'

NUKE_WAIT_TIME = 420

TERRAN_TEAM_COLOR = {r=255,g=255,b=0}