---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 12/22/2020 7:15 PM
---

-- Globals within the mod
MOD_NAME = 'erm_terran'
FORCE_NAME = 'enemy_erm_terran'
MOD_VERSION = 100

DEBUG_MODE = false
