---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 12/22/2020 7:15 PM
---

-- Globals within the mod
MOD_NAME = 'erm_terran'

DEBUG_MODE = false

TERRAN_TEAM_COLOR = {r=255,g=255,b=0}