---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 12/3/2022 11:00 PM
---

---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 2/9/2021 6:53 PM
---
require('__stdlib__/stdlib/utils/defines/time')
require('util')
local math3d = require "math3d"
local Sprites = require('__stdlib__/stdlib/data/modules/sprites')

require('__erm_terran__/global')

local ERM_UnitTint = require('__enemyracemanager__/lib/rig/unit_tint')

local ERM_Config = require('__enemyracemanager__/lib/global_config')
local ERMPlayerUnitHelper = require('__enemyracemanager__/lib/rig/player_unit_helper')

local DataHelper = require('__erm_terran__/prototypes/data_helper')

local TerranSound = require('__erm_terran_hd_assets__/sound')
local AnimationDB = require('__erm_terran_hd_assets__/animation_db')

local name = 'ghost'

-- Misc Settings
local attack_range = ERMPlayerUnitHelper.get_attack_range(1)
local vision_distance = ERMPlayerUnitHelper.get_vision_distance(attack_range)
local pollution_to_join_attack = 250
local distraction_cooldown = 30

-- Animation Settings
local unit_scale = 1.5

local collision_box = { { -0.5, -0.5 }, { 0.5, 0.5 } }
local selection_box = { { -0.75, -0.75 }, { 0.75, 0.75 } }

local regular_resist = DataHelper.getResistance(65)
local nuke_resist = DataHelper.getResistance(75)


local attackAnimation = AnimationDB.get_layered_animations('units', 'ghost', 'attack')

attackAnimation = AnimationDB.apply_runtime_tint(attackAnimation, true)

local runningAnimation = AnimationDB.get_layered_animations('units', 'ghost', 'run')

runningAnimation = AnimationDB.apply_runtime_tint(runningAnimation, true)

-- Firebat MK 1 --
data:extend({
    {
        type = "unit",
        name = MOD_NAME .. '/' .. name .. '/regular',
        localised_name = { 'entity-name.' .. MOD_NAME .. '/' .. name, 'Regular'},
        localised_description = { 'entity-description.' .. MOD_NAME .. '/' .. name},
        icons = {
            {
                icon = "__erm_terran_hd_assets__/graphics/entity/icons/units/"..name..".png",
                icon_size = 64,
            },
            {
                icon = "__base__/graphics/icons/signal/signal_1.png",
                icon_size = 64,
                scale = 0.25,
                shift = {-9,-9}
            },
        },
        flags = { "placeable-enemy", "placeable-player", "placeable-off-grid", "player-creation", "breaths-air" },
        has_belt_immunity = false,
        max_health = 60 * ERMPlayerUnitHelper.get_health_multiplier(),
        order = MOD_NAME .. name,
        subgroup = "erm_controllable_units",
        shooting_cursor_size = 2,
        resistances = regular_resist,
        healing_per_tick = 0,
        collision_box = collision_box,
        selection_box = selection_box,
        sticker_box = selection_box,
        vision_distance = vision_distance,
        movement_speed = 0.175 * ERMPlayerUnitHelper.get_speed_multiplier(),
        repair_speed_modifier = 1,
        pollution_to_join_attack = pollution_to_join_attack,
        distraction_cooldown = distraction_cooldown,
        can_open_gates = true,
        --ai_settings = biter_ai_settings,
        radar_range = 1,
        attack_parameters = {
            type = "projectile",
            range_mode = "bounding-box-to-bounding-box",
            ammo_category = 'flamethrower',
            range = 2,
            cooldown = 60,
            cooldown_deviation = 0.1,
            damage_modifier = ERMPlayerUnitHelper.get_damage_multiplier(),
            sound = TerranSound.firebat_attack(0.66, 0.33),
            ammo_type =
            {
                category = "flamethrower",
                action = {
                    type = "line",
                    force = 'not-same',
                    range = 3,
                    width = 2,
                    ignore_collision_condition = true,
                    action_delivery = {
                        type = "instant",
                        target_effects =
                        {
                            {
                                type = "damage",
                                damage = { amount = 75, type = "fire"}
                            },
                            {
                                type = "damage",
                                damage = { amount = 75, type = "explosion"}
                            },
                            {
                                type = "create-sticker",
                                sticker = "firebat-sticker",
                                show_in_tooltip = true
                            },
                        }
                    }
                },
            },
            animation = attackAnimation
        },
        distance_per_frame = 0.16,
        run_animation = runningAnimation,
        dying_trigger_effect = {
            {
                type = "nested-result",
                action =
                {
                    type = "area",
                    radius = 4,
                    force = 'not-same',
                    action_delivery =
                    {
                        type = "instant",
                        target_effects =
                        {
                            {
                                type = "damage",
                                damage = {amount = 200 * ERMPlayerUnitHelper.get_damage_multiplier() , type = "fire"}
                            },
                            {
                                type = "damage",
                                damage = {amount = 300 * ERMPlayerUnitHelper.get_damage_multiplier() , type = "explosion"}
                            }
                        }
                    }
                }
            }
        },
        dying_sound = TerranSound.firebat_death(1),
        corpse = name .. '-corpse',
        map_color = ERM_UnitTint.tint_army_color(),
        enemy_map_color = { r=1, b=0, g=0 },
    },
    {
        type = "corpse",
        name = name .. '-corpse',
        icon = "__erm_terran_hd_assets__/graphics/entity/icons/units/" .. name .. ".png",
        icon_size = 64,
        flags = { "placeable-off-grid", "building-direction-8-way", "not-on-map" },
        selection_box = selection_box,
        selectable_in_game = false,
        dying_speed = 0.04,
        time_before_removed = defines.time.second,
        subgroup = "corpses",
        order = "x" .. name,
        animation = Sprites.empty_pictures(),
    },
})

-- Ghost Mass Destruction --
local ghost_nuke = util.table.deepcopy(data.raw["unit"][MOD_NAME .. '/' .. name .. '/regular'])

ghost_nuke.name = MOD_NAME .. '/' .. name .. '/nuke'
ghost_nuke.localised_name = { 'entity-name.' .. MOD_NAME .. '/' .. name, 'Mass Destruction'}
ghost_nuke['icons'][2] = {
    icon = "__base__/graphics/icons/atomic-bomb.png",
    icon_size = 64,
    scale = 0.25,
    shift = {-9,-9}
}
ghost_nuke.movement_speed = 0.225 * ERMPlayerUnitHelper.get_speed_multiplier()
ghost_nuke.max_health = 200 * ERMPlayerUnitHelper.get_health_multiplier()
ghost_nuke.resistances = nuke_resist
ghost_nuke['attack_parameters']['damage_modifier'] = 1 + ERMPlayerUnitHelper.get_damage_multiplier()

data:extend({ ghost_nuke })


