---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 10/17/2021 9:54 PM
---
local Sprites = require('__stdlib__/stdlib/data/modules/sprites')
data:extend({
    {
        type = "projectile",
        name = "wraith-rocket",
        flags = { "not-on-map" },
        acceleration = 0.005,
        action = {
            type = "direct",
            action_delivery = {
                type = "instant",
                target_effects = {
                    {
                        type = "create-entity",
                        entity_name = "explosion"
                    },
                    {
                        type = "create-entity",
                        entity_name = "small-scorchmark-tintable",
                        check_buildability = true
                    },
                    {
                        type = "destroy-decoratives",
                        from_render_layer = "decorative",
                        to_render_layer = "object",
                        include_soft_decoratives = true, -- soft decoratives are decoratives with grows_through_rail_path = true
                        include_decals = false,
                        invoke_decorative_trigger = true,
                        decoratives_with_trigger_only = false, -- if true, destroys only decoratives that have trigger_effect set
                        radius = 1.5 -- large radius for demostrative purposes
                    },
                    {
                        type = "damage",
                        damage = { amount = 50, type = "physical" }
                    },
                    {
                        type = "nested-result",
                        action = {
                            type = "area",
                            force = "not-same",
                            radius = 3,
                            ignore_collision_condition = true,
                            action_delivery = {
                                type = "instant",
                                target_effects = {
                                    {
                                        type = "damage",
                                        damage = { amount = 175, type = "explosion" },
                                        apply_damage_to_trees = true,
                                    },
                                }
                            }
                        }
                    }
                }
            }
        },
        --light = {intensity = 0.5, size = 4},
        animation = {
            filename = "__base__/graphics/entity/rocket/rocket.png",
            draw_as_glow = true,
            frame_count = 8,
            line_length = 8,
            width = 9,
            height = 35,
            shift = { 0, 0 },
            priority = "high"
        },
        shadow = {
            filename = "__base__/graphics/entity/rocket/rocket-shadow.png",
            frame_count = 1,
            width = 7,
            height = 24,
            priority = "high",
            shift = { 0, 0 }
        },
        smoke = {
            {
                name = "smoke-fast",
                deviation = { 0.15, 0.15 },
                frequency = 1,
                position = { 0, 1 },
                slow_down_factor = 1,
                starting_frame = 3,
                starting_frame_deviation = 5,
                starting_frame_speed = 0,
                starting_frame_speed_deviation = 5
            }
        }
    },
    {
        type = "projectile",
        name = "wraith-laser-projectile",
        flags = { "not-on-map" },
        acceleration = 0.01,
        action = {
            type = "direct",
            action_delivery = {
                type = "instant",
                target_effects = {
                    {
                        type = "damage",
                        damage = { amount = 150, type = "laser" }
                    },
                }
            }
        },
        animation = {
            filename = "__erm_terran__/graphics/entity/units/battlecruiser/battlecruiser-laser-projectile.png",
            priority = "extra-high",
            width = 64,
            height = 64,
            frame_count = 1,
            animation_speed = 0.2,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 1.5,
            draw_as_glow = true,
        }
    },
    {
        type = "projectile",
        name = "battlecruiser-laser-projectile",
        flags = { "not-on-map" },
        acceleration = 0.01,
        action = {
            type = "direct",
            action_delivery = {
                type = "instant",
                target_effects = {
                    {
                        type = "damage",
                        damage = { amount = 300, type = "laser" }
                    },
                }
            }
        },
        animation = {
            filename = "__erm_terran__/graphics/entity/units/battlecruiser/battlecruiser-laser-projectile.png",
            priority = "extra-high",
            width = 64,
            height = 64,
            frame_count = 1,
            animation_speed = 0.2,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 1.5,
            draw_as_glow = true,
        }
    },
    {
        type = "projectile",
        name = "battlecruiser-yamato-projectile",
        flags = { "not-on-map" },
        acceleration = 0.01,
        action = {
            type = "direct",
            action_delivery = {
                type = "instant",
                target_effects = {
                    {
                        type = "create-entity",
                        entity_name = "medium-explosion"
                    },
                    {
                        type = "damage",
                        damage = { amount = 750, type = "laser" }
                    },
                    {
                        type = "nested-result",
                        action = {
                            type = "area",
                            force = "not-same",
                            radius = 4,
                            ignore_collision_condition = true,
                            action_delivery = {
                                type = "instant",
                                target_effects = {
                                    {
                                        type = "damage",
                                        damage = { amount = 125, type = "explosion" },
                                        apply_damage_to_trees = true,
                                    },
                                    {
                                        type = "damage",
                                        damage = { amount = 125, type = "electric" },
                                        apply_damage_to_trees = true,
                                    },
                                    {
                                        type = "destroy-decoratives",
                                        from_render_layer = "decorative",
                                        to_render_layer = "object",
                                        include_soft_decoratives = true, -- soft decoratives are decoratives with grows_through_rail_path = true
                                        include_decals = false,
                                        invoke_decorative_trigger = true,
                                        decoratives_with_trigger_only = false, -- if true, destroys only decoratives that have trigger_effect set
                                        radius = 3 -- large radius for demostrative purposes
                                    }
                                },
                            }
                        }
                    }
                }
            }
        },
        animation = {
            filename = "__erm_terran__/graphics/entity/units/battlecruiser/battlecruiser-projectile.png",
            priority = "extra-high",
            width = 96,
            height = 96,
            frame_count = 1,
            animation_speed = 0.2,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 1.25,
            draw_as_glow = true,
        }
    },
    {
        type = "projectile",
        name = "terran-tank-explosive-cannon-projectile",
        flags = {"not-on-map"},
        acceleration = 0,
        action =
        {
            type = "direct",
            action_delivery =
            {
                type = "instant",
                target_effects =
                {
                    {
                        type = "damage",
                        damage = {amount = 100, type = "physical"}
                    },
                    {
                        type = "create-entity",
                        entity_name = "explosion"
                    }
                }
            }
        },
        final_action =
        {
            type = "direct",
            action_delivery =
            {
                type = "instant",
                target_effects =
                {
                    {
                        type = "create-entity",
                        entity_name = "big-explosion"
                    },
                    --- Heavy ground AOE damage
                    {
                        type = "nested-result",
                        action =
                        {
                            type = "area",
                            force = "not-same",
                            radius = 5,
                            action_delivery =
                            {
                                type = "instant",
                                target_effects =
                                {
                                    {
                                        type = "damage",
                                        damage = {amount = 100, type = "explosion"},
                                        apply_damage_to_trees = true,
                                    },
                                    {
                                        type = "create-entity",
                                        entity_name = "explosion"
                                    }
                                }
                            }
                        }
                    },
                    --- Minor Air unit damage
                    {
                        type = "nested-result",
                        action =
                        {
                            type = "area",
                            force = "not-same",
                            radius = 2,
                            ignore_collision_condition = true,
                            action_delivery =
                            {
                                type = "instant",
                                target_effects =
                                {
                                    {
                                        type = "damage",
                                        damage = {amount = 50, type = "explosion"},
                                        apply_damage_to_trees = true,
                                    },
                                    {
                                        type = "create-entity",
                                        entity_name = "explosion"
                                    }
                                }
                            }
                        }
                    },
                    {
                        type = "create-entity",
                        entity_name = "medium-scorchmark-tintable",
                        check_buildability = true
                    },
                    {
                        type = "invoke-tile-trigger",
                        repeat_count = 1
                    },
                    {
                        type = "destroy-decoratives",
                        from_render_layer = "decorative",
                        to_render_layer = "object",
                        include_soft_decoratives = true, -- soft decoratives are decoratives with grows_through_rail_path = true
                        include_decals = false,
                        invoke_decorative_trigger = true,
                        decoratives_with_trigger_only = false, -- if true, destroys only decoratives that have trigger_effect set
                        radius = 3 -- large radius for demostrative purposes
                    }
                }
            }
        },
        animation =
        {
            filename = "__base__/graphics/entity/bullet/bullet.png",
            draw_as_glow = true,
            frame_count = 1,
            width = 3,
            height = 50,
            priority = "high"
        }
    }
})
