---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 10/17/2021 9:54 PM
---
require('__erm_terran__/global')
local AnimationDB = require('__erm_terran_hd_assets__/animation_db')

data:extend({
    {
        type = "projectile",
        name = "wraith-rocket",
        flags = { "not-on-map" },
        acceleration = 0.005,
        action = {
            type = "direct",
            action_delivery = {
                type = "instant",
                target_effects = {
                    {
                        type = "create-entity",
                        entity_name = "medium-explosion"
                    },
                    {
                        type = "create-entity",
                        entity_name = "small-scorchmark-tintable",
                        check_buildability = true
                    },
                    {
                        type = "destroy-decoratives",
                        from_render_layer = "decorative",
                        to_render_layer = "object",
                        include_soft_decoratives = true, -- soft decoratives are decoratives with grows_through_rail_path = true
                        include_decals = false,
                        invoke_decorative_trigger = true,
                        decoratives_with_trigger_only = false, -- if true, destroys only decoratives that have trigger_effect set
                        radius = 1.5 -- large radius for demostrative purposes
                    },
                    {
                        type = "damage",
                        damage = { amount = 50, type = "physical" }
                    },
                    {
                        type = "nested-result",
                        action = {
                            type = "area",
                            force = "not-same",
                            radius = 3,
                            ignore_collision_condition = true,
                            action_delivery = {
                                type = "instant",
                                target_effects = {
                                    {
                                        type = "damage",
                                        damage = { amount = 175, type = "explosion" },
                                        apply_damage_to_trees = true,
                                    },
                                }
                            }
                        }
                    }
                }
            }
        },
        --light = {intensity = 0.5, size = 4},
        animation = {
            filename = "__base__/graphics/entity/rocket/rocket.png",
            draw_as_glow = true,
            frame_count = 8,
            line_length = 8,
            width = 9,
            height = 35,
            shift = { 0, 0 },
        },
        shadow = {
            filename = "__base__/graphics/entity/rocket/rocket-shadow.png",
            frame_count = 1,
            width = 7,
            height = 24,
            shift = { 0, 0 }
        },
        smoke = {
            {
                name = "smoke-fast",
                deviation = { 0.15, 0.15 },
                frequency = 1 / 5,
                position = { 0, 1 },
                slow_down_factor = 1,
                starting_frame = 3,
                starting_frame_deviation = 5,
                starting_frame_speed = 0,
                starting_frame_speed_deviation = 5
            }
        }
    },
    {
        type = "projectile",
        name = "wraith-laser-projectile",
        flags = { "not-on-map" },
        acceleration = 0.01,
        action = {
            type = "direct",
            action_delivery = {
                type = "instant",
                target_effects = {
                    {
                        type = "damage",
                        damage = { amount = 150, type = "laser" }
                    },
                }
            }
        },
        animation = {
            filename = "__erm_terran__/graphics/entity/units/battlecruiser/battlecruiser-laser-projectile.png",
            width = 64,
            height = 64,
            frame_count = 1,
            animation_speed = 0.2,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 1.5,
            draw_as_glow = true,
        }
    },
    {
        type = "projectile",
        name = "battlecruiser-laser-projectile",
        flags = { "not-on-map" },
        acceleration = 0.01,
        action = {
            type = "direct",
            action_delivery = {
                type = "instant",
                target_effects = {
                    {
                        type = "damage",
                        damage = { amount = 300, type = "laser" }
                    },
                }
            }
        },
        animation = {
            filename = "__erm_terran__/graphics/entity/units/battlecruiser/battlecruiser-laser-projectile.png",
            width = 64,
            height = 64,
            frame_count = 1,
            animation_speed = 0.2,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 1.5,
            draw_as_glow = true,
        }
    },
    {
        type = "projectile",
        name = "battlecruiser-yamato-projectile",
        flags = { "not-on-map" },
        acceleration = 0.01,
        action = {
            type = "direct",
            action_delivery = {
                type = "instant",
                target_effects = {
                    {
                        type = "create-entity",
                        entity_name = "medium-explosion"
                    },
                    {
                        type = "damage",
                        damage = { amount = 750, type = "laser" }
                    },
                    {
                        type = "nested-result",
                        action = {
                            type = "area",
                            force = "not-same",
                            radius = 4,
                            ignore_collision_condition = true,
                            action_delivery = {
                                type = "instant",
                                target_effects = {
                                    {
                                        type = "damage",
                                        damage = { amount = 125, type = "explosion" },
                                        apply_damage_to_trees = true,
                                    },
                                    {
                                        type = "damage",
                                        damage = { amount = 125, type = "electric" },
                                        apply_damage_to_trees = true,
                                    },
                                    {
                                        type = "destroy-decoratives",
                                        from_render_layer = "decorative",
                                        to_render_layer = "object",
                                        include_soft_decoratives = true, -- soft decoratives are decoratives with grows_through_rail_path = true
                                        include_decals = false,
                                        invoke_decorative_trigger = true,
                                        decoratives_with_trigger_only = false, -- if true, destroys only decoratives that have trigger_effect set
                                        radius = 5 -- large radius for demostrative purposes
                                    }
                                },
                            }
                        }
                    }
                }
            }
        },
        animation = {
            filename = "__erm_terran__/graphics/entity/units/battlecruiser/battlecruiser-projectile.png",
            width = 96,
            height = 96,
            frame_count = 1,
            animation_speed = 0.2,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 1.25,
            draw_as_glow = true,
        }
    },
    {
        type = "projectile",
        name = "terran-tank-explosive-cannon-projectile",
        flags = {"not-on-map"},
        acceleration = 0,
        action =
        {
            type = "direct",
            action_delivery =
            {
                type = "instant",
                target_effects =
                {
                    {
                        type = "damage",
                        damage = {amount = 100, type = "physical"}
                    },
                    {
                        type = "create-entity",
                        entity_name = "explosion"
                    }
                }
            }
        },
        final_action =
        {
            type = "direct",
            action_delivery =
            {
                type = "instant",
                target_effects =
                {
                    {
                        type = "create-entity",
                        entity_name = "big-explosion"
                    },
                    --- Heavy ground AOE damage
                    {
                        type = "nested-result",
                        action =
                        {
                            type = "area",
                            force = "not-same",
                            radius = 5,
                            action_delivery =
                            {
                                type = "instant",
                                target_effects =
                                {
                                    {
                                        type = "damage",
                                        damage = {amount = 100, type = "explosion"},
                                        apply_damage_to_trees = true,
                                    },
                                    {
                                        type = "create-entity",
                                        entity_name = "explosion"
                                    }
                                }
                            }
                        }
                    },
                    --- Minor Air unit damage
                    {
                        type = "nested-result",
                        action =
                        {
                            type = "area",
                            force = "not-same",
                            radius = 2,
                            ignore_collision_condition = true,
                            action_delivery =
                            {
                                type = "instant",
                                target_effects =
                                {
                                    {
                                        type = "damage",
                                        damage = {amount = 50, type = "explosion"},
                                        apply_damage_to_trees = true,
                                    },
                                    {
                                        type = "create-entity",
                                        entity_name = "explosion"
                                    }
                                }
                            }
                        }
                    },
                    {
                        type = "create-entity",
                        entity_name = "medium-scorchmark-tintable",
                        check_buildability = true
                    },
                    {
                        type = "invoke-tile-trigger",
                        repeat_count = 1
                    },
                    {
                        type = "destroy-decoratives",
                        from_render_layer = "decorative",
                        to_render_layer = "object",
                        include_soft_decoratives = true, -- soft decoratives are decoratives with grows_through_rail_path = true
                        include_decals = false,
                        invoke_decorative_trigger = true,
                        decoratives_with_trigger_only = false, -- if true, destroys only decoratives that have trigger_effect set
                        radius = 5 -- large radius for demostrative purposes
                    }
                }
            }
        },
        animation =
        {
            filename = "__base__/graphics/entity/bullet/bullet.png",
            draw_as_glow = true,
            frame_count = 1,
            width = 3,
            height = 50,
        }
    },
    {
        type = "explosion",
        name = MOD_NAME.."/firebat-explosion",
        flags = { "not-on-map" },
        subgroup = 'explosions',
        order = MOD_NAME.."/firebat-explosion",
        animations = AnimationDB.get_layered_animations('death', 'firebat', 'explosion'),
    },
    {
        type = "explosion",
        name = "erm-terran-large-explosion",
        flags = { "not-on-map" },
        subgroup = 'explosions',
        order = "erm-terran-large-explosion",
        animations = {
            filename = "__erm_terran__/graphics/entity/explosion/large-explosion.png",
            width = 200,
            height = 200,
            frame_count = 10,
            animation_speed = 0.25,
            direction_count = 1,
            scale = 1.25,
            draw_as_glow = true,
        },
        --light = {intensity = 1, size = 50, color = {r=1.0, g=1.0, b=1.0}},
    },
    {
        type = "explosion",
        name = "erm-terran-building-large-explosion",
        flags = { "not-on-map" },
        subgroup = 'explosions',
        order = "erm-terran-large-explosion",
        animations = {
            filename = "__erm_terran__/graphics/entity/explosion/large-explosion.png",
            width = 200,
            height = 200,
            frame_count = 10,
            animation_speed = 0.25,
            direction_count = 1,
            scale = 1.25,
            draw_as_glow = true,
            shift = {0, 1}
        },
        --light = {intensity = 1, size = 50, color = {r=1.0, g=1.0, b=1.0}},
    },
    {
        type = "explosion",
        name = "erm-terran-building-xlarge-explosion",
        flags = { "not-on-map" },
        subgroup = 'explosions',
        order = "erm-terran-xlarge-explosion",
        animations = {
            filename = "__erm_terran__/graphics/entity/explosion/xlarge-explosion.png",
            width = 252,
            height = 200,
            frame_count = 10,
            animation_speed = 0.25,
            direction_count = 1,
            scale = 1.25,
            draw_as_glow = true,
            shift = {0, 1}
        },
        --light = {intensity = 1, size = 50, color = {r=1.0, g=1.0, b=1.0}},
    },
    {
        type = "corpse",
        name = "terran-large-base-corpse",
        flags = { "placeable-neutral",  "not-on-map" },
        icon = "__erm_terran__/graphics/entity/icons/advisor.png",
        icon_size = 64,
        collision_box = { { -2, -2 }, { 2, 2 } },
        selection_box = { { -2, -2 }, { 2, 2 } },
        selectable_in_game = false,
        dying_speed = 0.04,
        time_before_removed = defines.time.minute * settings.startup["enemyracemanager-enemy-corpse-time"].value,
        subgroup = "corpses",
        order = "c[corpse]-c[large-terran-base-corpse]",
        final_render_layer = "remnants",
        animation = {
            {
                filename = "__erm_terran__/graphics/entity/buildings/large-rubble.png",
                width = 128,
                height = 128,
                variation_count = 1,
                frame_count = 1,
                direction_count = 1,
                scale = 1.5,
            }
        }
    },
})
