---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 8/13/2023 3:27 PM
---

---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 8/13/2023 3:27 PM
---

require('__stdlib__/stdlib/utils/defines/time')
require('util')
local Sprites = require('__stdlib__/stdlib/data/modules/sprites')

require('__erm_terran__/global')

local ERM_UnitTint = require('__enemyracemanager__/lib/rig/unit_tint')

local ERM_Config = require('__enemyracemanager__/lib/global_config')
local ERMDataHelper = require('__enemyracemanager__/lib/rig/data_helper')
local ERMPlayerUnitHelper = require('__enemyracemanager__/lib/rig/player_unit_helper')
local TerranSound = require('__erm_terran_hd_assets__/sound')
local AnimationDB = require('__erm_terran_hd_assets__/animation_db')
local name = 'science_vessel'

local attack_range = ERMPlayerUnitHelper.get_attack_range(1,4)

-- Misc Settings
local vision_distance = ERMPlayerUnitHelper.get_vision_distance(attack_range)
local pollution_to_join_attack = 250
local distraction_cooldown = 30

-- Animation Settings
local unit_scale = 1.5

local collision_box = { { -1, -1 }, { 1, 1 } }
local selection_box = { { -1, -1 }, { 1, 1 } }

local runAnimation = AnimationDB.get_layered_animations('units', 'science_vessel_body', 'run')
local runTurretAnimation = AnimationDB.get_layered_animations('units', 'science_vessel_turret', 'run')

for _, ani_data in pairs(runTurretAnimation['layers']) do
    table.insert(runAnimation['layers'],ani_data)
end

runAnimation = AnimationDB.apply_runtime_tint(runAnimation, true)

local attackAnimation = AnimationDB.get_layered_animations('units', 'science_vessel_body', 'attack')
local attackTurretAnimation = AnimationDB.get_layered_animations('units', 'science_vessel_turret', 'attack')

for _, ani_data in pairs(attackTurretAnimation['layers']) do
    table.insert(attackAnimation['layers'],ani_data)
end

attackAnimation = AnimationDB.apply_runtime_tint(attackAnimation, true)



data:extend({
    {
        type = "unit",
        name = MOD_NAME .. '/' .. name,
        icons = {
            {
                icon = "__erm_terran_hd_assets__/graphics/entity/icons/units/"..name.."256.png",
                icon_size = 256,
            }
        },
        flags = { "placeable-enemy", "placeable-player", "placeable-off-grid", "player-creation", "not-flammable" },
        has_belt_immunity = true,
        max_health = 200 * ERMPlayerUnitHelper.get_health_multiplier(),
        order = MOD_NAME .. "/" .. name,
        subgroup = "erm_controllable_units",
        shooting_cursor_size = 2,
        can_open_gates = true,
        resistances = {
            { type = "acid", percent = 75 },
            { type = "poison", percent = 100 },
            { type = "physical", percent = 75 },
            { type = "fire", percent = 75 },
            { type = "explosion", percent = 75 },
            { type = "laser", percent = 75 },
            { type = "electric", percent = 75 },
            { type = "cold", percent = 75 }
        },
        healing_per_tick = 0,
        collision_mask = ERMDataHelper.getFlyingCollisionMask(),
        collision_box = collision_box,
        selection_box = selection_box,
        sticker_box = selection_box,
        vision_distance = vision_distance,
        movement_speed = 0.25 * ERMPlayerUnitHelper.get_speed_multiplier(),
        repair_speed_modifier = 0.33,
        pollution_to_join_attack = pollution_to_join_attack,
        distraction_cooldown = distraction_cooldown,
        --ai_settings = biter_ai_settings,
        radar_range = 2,
        attack_parameters = {
            type = "projectile",
            range_mode = "bounding-box-to-bounding-box",
            ammo_category = 'shotgun-shell',
            range = attack_range,
            min_attack_distance = attack_range - 4,
            cooldown = 300,
            cooldown_deviation = 0.2,
            warmup = 6,
            damage_modifier = ERMPlayerUnitHelper.get_damage_multiplier(),
            sound = TerranSound.science_vessel_irradiate(0.5),
            ammo_type =
            {
                category = "shotgun-shell",
                action =
                {
                    {
                        type = "direct",
                        action_delivery = {
                            type = "instant",
                            target_effects = {
                                {
                                    type = "damage",
                                    damage = {amount = 250, type = "acid"},
                                    apply_damage_to_trees = true,
                                },
                                {
                                    type = "create-fire",
                                    show_in_tooltip = true,
                                    entity_name = MOD_NAME..'/science-vessel-irradiate-cloud',
                                },
                            }
                        }
                    }
                },
            },
            animation = attackAnimation,
        },
        distance_per_frame = 0.2,
        render_layer = "wires-above",
        run_animation = runAnimation,
        dying_explosion = "erm-fire-explosion-air_large-1",
        dying_sound = TerranSound.enemy_death(name, 0.75),
        corpse = MOD_NAME..'/'..name .. '-corpse',
        map_color = ERM_UnitTint.tint_army_color(),
        enemy_map_color = { r=1, b=0, g=0 },
    },
    {
        type = "corpse",
        name = MOD_NAME..'/'..name .. '-corpse',
        icon = "__erm_terran_hd_assets__/graphics/entity/icons/units/" .. name .. ".png",
        icon_size = 64,
        flags = { "placeable-off-grid", "building-direction-8-way", "not-on-map" },
        selection_box = selection_box,
        selectable_in_game = false,
        dying_speed = 0.04,
        time_before_removed = defines.time.second,
        subgroup = "corpses",
        order = "x" .. name,
        animation = Sprites.empty_pictures(),
    },
    {
        type = "fire",
        name = MOD_NAME..'/science-vessel-irradiate-cloud',
        flags = {"placeable-off-grid", "not-on-map"},
        damage_per_tick  = { amount = 0 / 60, type= 'acid' },
        on_damage_tick_effect  =                         {
            type = "area",
            radius = 3.0,
            force = "not-same",
            ignore_collision_condition = true,
            action_delivery =
            {
                type = "instant",
                target_effects =
                {
                    {
                        type = "damage",
                        damage = {amount = 2000 / 60 , type = "poison"}
                    },
                    {
                        type = "create-sticker",
                        sticker = "5-075-slowdown-sticker",
                        show_in_tooltip = true,
                    }
                }
            }
        },

        pictures = AnimationDB.get_single_animation('projectiles', 'science_vessel_irradiate', 'explosion', 'glow'),

        spawn_entity = MOD_NAME..'/science-vessel-irradiate-cloud',

        maximum_damage_multiplier = 3,
        damage_multiplier_increase_per_added_fuel = 1,
        damage_multiplier_decrease_per_tick = 0.005,

        spread_delay = 60,
        spread_delay_deviation = 15,
        maximum_spread_count = 5,

        emissions_per_second = 0.01,

        initial_lifetime = 180,
        lifetime_increase_by = 180,
        lifetime_increase_cooldown = 60,
        maximum_lifetime = 540,
        --delay_between_initial_flames = 10,
        --initial_flame_count = 1,

    }
    --{
    --    name = MOD_NAME..'/science-vessel-irradiate-cloud',
    --    type = "smoke-with-trigger",
    --    flags = { "not-on-map" },
    --    show_when_smoke_off = true,
    --    particle_count = 1,
    --    --particle_spread = { 3.6 * 1.05, 3.6 * 0.6 * 1.05 },
    --    --particle_distance_scale_factor = 0.5,
    --    --particle_scale_factor = { 1, 0.707 },
    --    --wave_speed = { 1/80, 1/60 },
    --    --wave_distance = { 0.3, 0.2 },
    --    --spread_duration_variation = 20,
    --    --particle_duration_variation = 60 * 3,
    --    render_layer = "explosion",
    --
    --    affected_by_wind = false,
    --    duration = 180,
    --    cyclic = true,
    --    --spread_duration = 20,
    --
    --    animation = AnimationDB.get_single_animation('projectiles', 'science_vessel_irradiate', 'explosion', 'glow'),
    --    action = {
    --        type = "direct",
    --        action_delivery = {
    --            type = "instant",
    --            target_effects = {
    --                type = "nested-result",
    --                action = {
    --                    type = "area",
    --                    force = 'not-same',
    --                    radius = 3,
    --                    ignore_collision_condition = true,
    --                    action_delivery = {
    --                        type = "instant",
    --                        target_effects = {
    --                            {
    --                                type = "damage",
    --                                damage = {amount = 100, type = "poison"},
    --                                apply_damage_to_trees = true,
    --                            },
    --                            {
    --                                type = "create-sticker",
    --                                sticker = "5-075-slowdown-sticker",
    --                                show_in_tooltip = true,
    --                            }
    --                        }
    --                    }
    --                }
    --            }
    --        }
    --    },
    --    action_cooldown = 30
    --},
})
