---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 2/9/2021 6:53 PM
---
require('__stdlib__/stdlib/utils/defines/time')
require('util')
local Sprites = require('__stdlib__/stdlib/data/modules/sprites')

require('__erm_terran__/global')

local ERM_UnitTint = require('__enemyracemanager__/lib/rig/unit_tint')

local ERM_Config = require('__enemyracemanager__/lib/global_config')
local ERMDataHelper = require('__enemyracemanager__/lib/rig/data_helper')
local ERMPlayerUnitHelper = require('__enemyracemanager__/lib/rig/player_unit_helper')
local TerranSound = require('__erm_terran__/prototypes/sound')

local name = 'wraith'

local attack_range = 16

-- Misc Settings
local vision_distance = 35
local pollution_to_join_attack = 250
local distraction_cooldown = 30

-- Animation Settings
local unit_scale = 1.5

local collision_box = { { -0.75, -0.75 }, { 0.75, 0.75 } }
local selection_box = { { -1.0, -1.0 }, { 1.0, 1.0 } }

function wraith_animation(color)
    return
    {
        layers = {
            {
                filename = "__erm_terran__/graphics/entity/units/" .. name .. "/" .. name .. "-effect.png",
                width = 64,
                height = 64,
                frame_count = 2,
                axially_symmetrical = false,
                direction_count = 16,
                scale = unit_scale,
                animation_speed = 0.6,
                draw_as_glow = true,
                blend_mode = 'additive-soft',
                tint = ERM_UnitTint.tint_plane_burner(),
            },
            {
                filename = "__erm_terran__/graphics/entity/units/" .. name .. "/" .. name .. "-" .. color .. "-run.png",
                width = 64,
                height = 64,
                frame_count = 1,
                repeat_count = 2,
                axially_symmetrical = false,
                direction_count = 16,
                scale = unit_scale,
                animation_speed = 0.6,
            },
            {
                filename = "__erm_terran__/graphics/entity/units/" .. name .. "/" .. name .. "-" .. color .. "-run.png",
                width = 64,
                height = 64,
                frame_count = 1,
                repeat_count = 2,
                axially_symmetrical = false,
                direction_count = 16,
                scale = unit_scale,
                tint = ERM_UnitTint.tint_shadow(),
                animation_speed = 0.6,
                draw_as_shadow = true,
                shift = { 4, 0 }
            }
        }
    }
end


data:extend({
    {
        type = "unit",
        name = MOD_NAME .. '/' .. name,
        localised_name = { 'entity-name.' .. MOD_NAME .. '/' .. name },
        icons = {
            {
                icon = "__erm_terran__/graphics/entity/icons/units/"..name..".png",
                icon_size = 64,
            },
            {
                icon = "__base__/graphics/icons/signal/signal_red.png",
                icon_size = 64,
                scale = 0.2,
                shift = {-9,-9}
            },
        },
        flags = { "placeable-enemy", "placeable-player", "placeable-off-grid", "player-creation", "not-flammable" },
        has_belt_immunity = true,
        max_health = 200 * ERMPlayerUnitHelper.get_health_multiplier(),
        order = MOD_NAME .. name,
        subgroup = "erm_controllable_units",
        shooting_cursor_size = 2,
        radar_range = 2,
        resistances = {
            { type = "acid", percent = 75 },
            { type = "poison", percent = 100 },
            { type = "physical", percent = 75 },
            { type = "fire", percent = 75 },
            { type = "explosion", percent = 75 },
            { type = "laser", percent = 75 },
            { type = "electric", percent = 75 },
            { type = "cold", percent = 75 }
        },
        healing_per_tick = 0,
        collision_mask = ERMDataHelper.getFlyingCollisionMask(),
        collision_box = collision_box,
        selection_box = selection_box,
        sticker_box = selection_box,
        vision_distance = vision_distance,
        movement_speed = 0.3 * ERMPlayerUnitHelper.get_speed_multiplier(),
        repair_speed_modifier = 1,
        pollution_to_join_attack = pollution_to_join_attack,
        distraction_cooldown = distraction_cooldown,
        --ai_settings = biter_ai_settings,
        attack_parameters = {
            type = "projectile",
            range_mode = "bounding-box-to-bounding-box",
            ammo_category = 'rocket',
            range = attack_range,
            min_attack_distance = attack_range - 4,
            cooldown = 120,
            cooldown_deviation = 0.1,
            damage_modifier = ERMPlayerUnitHelper.get_damage_multiplier(),
            warmup = 6,
            ammo_type = {
                category = "rocket",
                target_type = "direction",
                action = {
                    type = "direct",
                    action_delivery = {
                        type = "projectile",
                        projectile = "wraith-rocket",
                        starting_speed = 0.3,
                        max_range = ERM_Config.get_max_projectile_range() * 2,
                    }
                }
            },
            animation = wraith_animation('orange'),
            sound = TerranSound.rapid_attack(name, 0.6, 0.5),
        },
        render_layer = "wires-above",
        distance_per_frame = 0.5,
        run_animation = wraith_animation('orange'),
        map_color = ERM_UnitTint.tint_army_color(),
        enemy_map_color = { r=1, b=0, g=0 },
        dying_explosion = 'erm-fire-explosion-air_normal-1',
        dying_sound = TerranSound.death(name, 1),
        corpse = name .. '-corpse'
    },
    {
        type = "corpse",
        name = name .. '-corpse',
        icon = "__erm_terran__/graphics/entity/icons/units/" .. name .. ".png",
        icon_size = 64,
        flags = { "placeable-off-grid", "building-direction-8-way", "not-on-map" },
        selection_box = selection_box,
        selectable_in_game = false,
        dying_speed = 0.04,
        time_before_removed = defines.time.second,
        subgroup = "corpses",
        order = "x" .. name,
        animation = Sprites.empty_pictures(),
    }
})

-- Scout Wraith --
local scout_wraith = util.table.deepcopy(data.raw["unit"][MOD_NAME .. '/' .. name])
scout_wraith.name = MOD_NAME .. '/' .. name .. '/scout'
scout_wraith.localised_name = { 'entity-name.' .. MOD_NAME .. '/' .. name .. '/scout'}
scout_wraith['icons'][2]['icon'] = "__base__/graphics/icons/signal/signal_S.png"
scout_wraith.movement_speed = 0.6 * ERMPlayerUnitHelper.get_speed_multiplier()
scout_wraith.attack_parameters = {
    type = "projectile",
    range_mode = "bounding-box-to-bounding-box",
    ammo_category = 'laser',
    range = attack_range,
    min_attack_distance = attack_range - 4,
    cooldown = 60,
    cooldown_deviation = 0.1,
    warmup = 6,
    damage_modifier = ERMPlayerUnitHelper.get_damage_multiplier(),
    ammo_type = {
        category = "laser",
        target_type = "direction",
        action = {
            type = "direct",
            action_delivery = {
                type = "projectile",
                projectile = "wraith-laser-projectile",
                starting_speed = 0.5,
            }
        }
    },
    sound = TerranSound.laser_attack('battlecruiser', 0.6, 0.75),
    animation = wraith_animation('yellow')
}

scout_wraith['run_animation'] = wraith_animation('yellow')

data:extend({scout_wraith})

-- Cold Wraith --
-- Cold explosion --
local cold_wraith_explosion = util.table.deepcopy(data.raw["explosion"]['explosion'])
cold_wraith_explosion['name'] = 'cold-explosion'
cold_wraith_explosion['localised_name'] = {"entity-name.cold-explosion"}
table.remove(cold_wraith_explosion['animations'], 1)
for i, animation in pairs(cold_wraith_explosion['animations']) do
    cold_wraith_explosion['animations'][i]['filename'] = "__erm_terran__/graphics/entity/explosion/bw-explosion-3.png"
    cold_wraith_explosion['animations'][i]['tint'] = ERM_UnitTint.tint_cold_explosion()
    cold_wraith_explosion['animations'][i]['scale'] = 1.5
    cold_wraith_explosion['animations'][i]['hr_version']['filename'] = "__erm_terran__/graphics/entity/explosion/bw-hr-explosion-3.png"
    cold_wraith_explosion['animations'][i]['hr_version']['tint'] = ERM_UnitTint.tint_cold_explosion()
    cold_wraith_explosion['animations'][i]['hr_version']['scale'] = 1.5
end
data:extend({cold_wraith_explosion})

-- Cold projectile --
local cold_wraith_projectile = util.table.deepcopy(data.raw["projectile"]['wraith-rocket'])
cold_wraith_projectile['name'] = 'cold-wraith-projectile'
cold_wraith_projectile['action']['action_delivery']
    ['target_effects'][1]['entity_name'] = 'cold-explosion'
cold_wraith_projectile['action']['action_delivery']
    ['target_effects'][5]['action']['action_delivery']
    ['target_effects'][1]['damage'] = { amount = 175, type = "cold" }
table.insert(
    cold_wraith_projectile['action']['action_delivery']['target_effects'],
{
        type = "create-sticker",
        sticker = "5-075-slowdown-sticker"
    }
)

data:extend({cold_wraith_projectile})

-- Cold entity --
local cold_wraith = util.table.deepcopy(data.raw["unit"][MOD_NAME .. '/' .. name])

cold_wraith.name = MOD_NAME .. '/' .. name .. '/cold'
cold_wraith.localised_name = { 'entity-name.' .. MOD_NAME .. '/' .. name .. '/cold'}
cold_wraith['icons'][2]['icon'] = "__base__/graphics/icons/signal/signal_blue.png"

cold_wraith['run_animation'] =  wraith_animation('blue')

cold_wraith['attack_parameters']['ammo_type']['action']['action_delivery']['projectile'] = 'cold-wraith-projectile'
cold_wraith['attack_parameters']['animation'] = wraith_animation('blue')

data:extend({cold_wraith})

-- Acid Wraith --
local acid_wraith_explosion = util.table.deepcopy(data.raw["explosion"]['explosion'])
acid_wraith_explosion['name'] = 'acid-explosion'
acid_wraith_explosion['localised_name'] = {"entity-name.acid-explosion"}
table.remove(acid_wraith_explosion['animations'], 1)
for i, animation in pairs(acid_wraith_explosion['animations']) do
    acid_wraith_explosion['animations'][i]['tint'] = ERM_UnitTint.tint_acid_explosion()
    acid_wraith_explosion['animations'][i]['scale'] = 1.5
    acid_wraith_explosion['animations'][i]['hr_version']['tint'] = ERM_UnitTint.tint_acid_explosion()
    acid_wraith_explosion['animations'][i]['hr_version']['scale'] = 1.5
end

data:extend({acid_wraith_explosion})

local acid_wraith_projectile = util.table.deepcopy(data.raw["projectile"]['wraith-rocket'])
acid_wraith_projectile['name'] = 'acid-wraith-projectile'
acid_wraith_projectile['action']['action_delivery']
    ['target_effects'][1]['entity_name'] = 'acid-explosion'
acid_wraith_projectile['action']['action_delivery']
    ['target_effects'][5]['action']['action_delivery']
    ['target_effects'][1]['damage'] = { amount = 175, type = "acid" }
acid_wraith_projectile['action']['action_delivery']
['target_effects'][5]['action']['radius'] = 4

data:extend({acid_wraith_projectile})

local acid_wraith = util.table.deepcopy(data.raw["unit"][MOD_NAME .. '/' .. name])
acid_wraith.name = MOD_NAME .. '/' .. name .. '/acid'
acid_wraith.localised_name = { 'entity-name.' .. MOD_NAME .. '/' .. name .. '/acid' }
acid_wraith['icons'][2]['icon'] = "__base__/graphics/icons/signal/signal_green.png"

acid_wraith['run_animation']['layers'][2] = {
    filename = "__erm_terran__/graphics/entity/units/" .. name .. "/" .. name .. "-green-run.png",
    width = 64,
    height = 64,
    frame_count = 1,
    repeat_count = 2,
    axially_symmetrical = false,
    direction_count = 16,
    scale = unit_scale,
    animation_speed = 0.6,
}
acid_wraith['attack_parameters']['ammo_type']
    ['action']['action_delivery']['projectile'] = 'acid-wraith-projectile'

acid_wraith['attack_parameters']['animation'] = wraith_animation('green')
acid_wraith['animation'] = wraith_animation('green')

data:extend({acid_wraith})