---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 11/2/2024 7:01 PM
---

local simulations = require("__erm_terran__/prototypes/tips_and_tricks/simulations")
local ERM_TERRAN = require("__erm_terran__/global")

data:extend(
        {
            {
                type = "tips-and-tricks-item-category",
                name = ERM_TERRAN.MOD_NAME,
                order = "n02-["..ERM_TERRAN.MOD_NAME.."]"
            },
            {
                type = "tips-and-tricks-item",
                name = ERM_TERRAN.MOD_NAME.."-general-info",
                tag = "[entity="..ERM_TERRAN.MOD_NAME.."--barrack]",
                category = ERM_TERRAN.MOD_NAME,
                order = "a",
                is_title = true,
                starting_status = "suggested",
                --simulation = simulations.general
            },
            {
                type = "tips-and-tricks-item",
                name = ERM_TERRAN.MOD_NAME.."-building",
                tag = "[entity="..ERM_TERRAN.MOD_NAME.."--factory]",
                category = ERM_TERRAN.MOD_NAME,
                order = "b",
                indent = 1,
                starting_status = "suggested",
                --simulation = simulations.general
            },
            {
                type = "tips-and-tricks-item",
                name = ERM_TERRAN.MOD_NAME.."-teleport",
                tag = "[entity="..ERM_TERRAN.MOD_NAME.."--command-center]",
                category = ERM_TERRAN.MOD_NAME,
                order = "d",
                indent = 1,                
                starting_status = "suggested",
                --simulation = simulations.general
            },
        }
)