---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 12/4/2022 2:27 AM
---

local DataHelper = {}

function DataHelper.getResistance(value)
    return {
        { type = "acid", percent = value },
        { type = "poison", percent = value },
        { type = "physical", percent = value },
        { type = "fire", percent = value },
        { type = "explosion", percent = value },
        { type = "laser", percent = value },
        { type = "electric", percent = value },
        { type = "cold", percent = value }
    }
end


return DataHelper