---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 2/9/2021 10:26 PM
---

local TerranSound = {}

function TerranSound.death(name, volume)
    return {
        filename = "__erm_terran__/sound/" .. name .. "/death.ogg",
        volume = volume
    }
end

function TerranSound.rapid_attack(name, volume, distance)
    return {
        aggregation = {
            max_count = 1,
            remove = true,
            count_already_playing = true,
        },
        audible_distance_modifier = distance,
        variations = {
            {
                filename = "__erm_terran__/sound/" .. name .. "/attack.ogg",
                volume = volume
            }
        }
    }
end

function TerranSound.attack(name, volume, distance)
    return {
        aggregation = {
            max_count = 1,
            remove = true,
            count_already_playing = true,
        },
        audible_distance_modifier = distance,
        variations = {
            {
                filename = "__erm_terran__/sound/" .. name .. "/attack.ogg",
                volume = volume
            }
        }
    }
end

function TerranSound.laser_attack(name, volume, distance)
    return {
        aggregation = {
            max_count = 1,
            remove = true,
            count_already_playing = true,
        },
        audible_distance_modifier = distance,
        variations = {
            {
                filename = "__erm_terran__/sound/" .. name .. "/laser_attack.ogg",
                volume = volume,
            }
        }
    }
end

function TerranSound.marine_death(volume)
    return {
        variations = {
            {
                filename = "__erm_terran__/sound/marine/death_1.ogg",
                volume = volume
            },
            {
                filename = "__erm_terran__/sound/marine/death_2.ogg",
                volume = volume
            },
        }
    }
end

function TerranSound.firebat_death(volume)
    return {
        variations = {
            {
                filename = "__erm_terran__/sound/firebat/death.ogg",
                volume = volume
            },
            {
                filename = "__erm_terran__/sound/firebat/death1.ogg",
                volume = volume
            },
            {
                filename = "__erm_terran__/sound/firebat/death2.ogg",
                volume = volume
            },
        }
    }
end

function TerranSound.firebat_attack(volume, distance)
    return {
        audible_distance_modifier = distance,
        variations = {
            {
                filename = "__erm_terran__/sound/firebat/attack.ogg",
                volume = volume
            },
            {
                filename = "__erm_terran__/sound/firebat/attack1.ogg",
                volume = volume
            },
        }
    }
end

return TerranSound;