---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 2/12/2021 8:20 PM
---

require('__erm_terran__/global')

data:extend({
    {
        type = "technology",
        name = MOD_NAME .. '/marine/mk-1',
        icon_size = 64,
        icon = "__erm_terran__/graphics/entity/icons/units/marine.png",
        effects =
        {
            {
                type = "unlock-recipe",
                recipe = MOD_NAME .. '/marine/mk1'
            },
        },
        prerequisites = {"military-2","military-science-pack", MOD_NAME .. '/barrack'},
        unit =
        {
            ingredients =
            {
                {"automation-science-pack", 1},
                {"logistic-science-pack", 1},
                {"military-science-pack", 1},
            },
            time = 30,
            count = 150
        },
    },
    {
        type = "technology",
        name = MOD_NAME .. '/marine/mk-2',
        icon_size = 64,
        icon = "__erm_terran__/graphics/entity/icons/units/marine.png",
        effects =
        {
            {
                type = "unlock-recipe",
                recipe = MOD_NAME .. '/marine/mk2'
            },
        },
        prerequisites = {"military-2","heavy-armor", MOD_NAME .. '/marine/mk-1', MOD_NAME .. '/barrack'},
        unit =
        {
            ingredients =
            {
                {"automation-science-pack", 1},
                {"logistic-science-pack", 1},
                {"chemical-science-pack", 1},
                {"military-science-pack", 1},
            },
            time = 45,
            count = 500
        },
    },
    {
        type = "technology",
        name = MOD_NAME .. '/marine/mk-3',
        icon_size = 64,
        icon = "__erm_terran__/graphics/entity/icons/units/marine.png",
        effects =
        {
            {
                type = "unlock-recipe",
                recipe = MOD_NAME .. '/marine/mk3'
            },
        },
        prerequisites = {"military-4","modular-armor",'uranium-ammo', MOD_NAME .. '/marine/mk-2', MOD_NAME .. '/barrack'},
        unit =
        {
            ingredients =
            {
                {"automation-science-pack", 1},
                {"logistic-science-pack", 1},
                {"chemical-science-pack", 1},
                {"military-science-pack", 1},
                {"utility-science-pack", 1}
            },
            time = 60,
            count = 1000
        },
    },
    {
        type = "technology",
        name = MOD_NAME .. '/firebat/mk-1',
        icon_size = 64,
        icon = "__erm_terran__/graphics/entity/icons/units/firebat.png",
        effects =
        {
            {
                type = "unlock-recipe",
                recipe = MOD_NAME .. '/firebat/mk1'
            },
        },
        prerequisites = {"military-2","military-science-pack", MOD_NAME .. '/barrack','flamethrower'},
        unit =
        {
            ingredients =
            {
                {"automation-science-pack", 1},
                {"logistic-science-pack", 1},
                {"military-science-pack", 1},
                {"chemical-science-pack", 1},
            },
            time = 30,
            count = 300
        },
    },
    {
        type = "technology",
        name = MOD_NAME .. '/firebat/mk-2',
        icon_size = 64,
        icon = "__erm_terran__/graphics/entity/icons/units/firebat.png",
        effects =
        {
            {
                type = "unlock-recipe",
                recipe = MOD_NAME .. '/firebat/mk2'
            },
        },
        prerequisites = {"military-4","modular-armor", 'refined-flammables-5',MOD_NAME .. '/firebat/mk-1', MOD_NAME .. '/barrack'},
        unit =
        {
            ingredients =
            {
                {"automation-science-pack", 1},
                {"logistic-science-pack", 1},
                {"chemical-science-pack", 1},
                {"military-science-pack", 1},
                {"utility-science-pack", 1}
            },
            time = 60,
            count = 1000
        },
    },
    {
        type = "technology",
        name = MOD_NAME .. '/tank/mk-1',
        icon_size = 64,
        icon = "__erm_terran__/graphics/entity/icons/units/tank.png",
        effects =
        {
            {
                type = "unlock-recipe",
                recipe = MOD_NAME .. '/tank'
            },
        },
        prerequisites = {
            "military-3", "tank", MOD_NAME .. '/factory',
             "low-density-structure", MOD_NAME .. '/marine/mk-2'
        },
        unit =
        {
            ingredients =
            {
                {"automation-science-pack", 1},
                {"logistic-science-pack", 1},
                {"chemical-science-pack", 1},
                {"military-science-pack", 1},
            },
            time = 45,
            count = 600
        },
    },
    {
        type = "technology",
        name = MOD_NAME .. '/tank/mk-2',
        icon_size = 64,
        icon = "__erm_terran__/graphics/entity/icons/units/tank.png",
        effects =
        {
            {
                type = "unlock-recipe",
                recipe = MOD_NAME .. '/tank/mk2'
            },
        },
        prerequisites = {
            "military-4", "tank", "rocket-control-unit", MOD_NAME .. '/tank/mk-1',
            "rocket-fuel", "low-density-structure", MOD_NAME .. '/factory',
        },
        unit =
        {
            ingredients =
            {
                {"automation-science-pack", 1},
                {"logistic-science-pack", 1},
                {"chemical-science-pack", 1},
                {"military-science-pack", 1},
                {"utility-science-pack", 1}
            },
            time = 60,
            count = 1200
        },
    },
    {
        type = "technology",
        name = MOD_NAME .. '/goliath',
        icon_size = 64,
        icon = "__erm_terran__/graphics/entity/icons/units/goliath.png",
        effects =
        {
            {
                type = "unlock-recipe",
                recipe = MOD_NAME .. '/goliath'
            },
        },
        prerequisites = {
            "military-4", "rocket-control-unit", 'exoskeleton-equipment', "electric-energy-accumulators",
            "rocketry","uranium-ammo", "low-density-structure", MOD_NAME .. '/factory',
        },
        unit =
        {
            ingredients =
            {
                {"automation-science-pack", 1},
                {"logistic-science-pack", 1},
                {"chemical-science-pack", 1},
                {"military-science-pack", 1},
                {"utility-science-pack", 1}
            },
            time = 60,
            count = 750
        },
    },
    {
        type = "technology",
        name = MOD_NAME .. '/wraith',
        icon_size = 64,
        icon = "__erm_terran__/graphics/entity/icons/units/wraith.png",
        effects =
        {
            {
                type = "unlock-recipe",
                recipe = MOD_NAME .. '/wraith'
            },
            {
                type = "unlock-recipe",
                recipe = MOD_NAME .. '/wraith/cold'
            },
            {
                type = "unlock-recipe",
                recipe = MOD_NAME .. '/wraith/acid'
            },
            {
                type = "unlock-recipe",
                recipe = MOD_NAME .. '/wraith/scout'
            },
        },
        prerequisites = {
            "military-4", "low-density-structure",
            "rocket-control-unit",  MOD_NAME .. '/marine/mk-2',
            "explosive-rocketry", "rocket-fuel", MOD_NAME .. '/starport'
        },
        unit =
        {
            ingredients =
            {
                {"automation-science-pack", 1},
                {"logistic-science-pack", 1},
                {"chemical-science-pack", 1},
                {"military-science-pack", 1},
                {"utility-science-pack", 1}
            },
            time = 60,
            count = 500
        },
    },
    {
        type = "technology",
        name = MOD_NAME .. '/battlecruiser',
        icon_size = 64,
        icon = "__erm_terran__/graphics/entity/icons/units/battlecruiser.png",
        effects =
        {
            {
                type = "unlock-recipe",
                recipe = MOD_NAME .. '/battlecruiser/yamato'
            },
            {
                type = "unlock-recipe",
                recipe = MOD_NAME .. '/battlecruiser/laser'
            },
        },
        prerequisites = {
            "military-4", "nuclear-power",
            "low-density-structure",  MOD_NAME .. '/marine/mk-3',
            "rocket-control-unit", "laser-turret", MOD_NAME .. '/starport'
        },
        unit =
        {
            ingredients =
            {
                {"automation-science-pack", 1},
                {"logistic-science-pack", 1},
                {"chemical-science-pack", 1},
                {"military-science-pack", 1},
                {"utility-science-pack", 1}
            },
            time = 60,
            count = 2500
        },
    },


    --- Buildings
    {
        type = "technology",
        name = MOD_NAME .. '/command-center',
        icons = {
            {
                icon = "__erm_terran__/graphics/entity/icons/advisor.png",
                icon_size = 64,
            },
            {
                icon = "__base__/graphics/icons/signal/signal_C.png",
                icon_size = 64,
                scale = 0.25,
                shift = {-20,-20}
            },
        },
        effects = {
            {
                type = "unlock-recipe",
                recipe = MOD_NAME .. '/command-center'
            },
        },
        prerequisites = {
            "military-4",
            "low-density-structure",
            "rocket-control-unit"
        },
        unit = {
            ingredients = {
                { "automation-science-pack", 1 },
                { "logistic-science-pack", 1 },
                { "chemical-science-pack", 1 },
                { "military-science-pack", 1 },
                { "utility-science-pack", 1 }
            },
            time = 30,
            count = 1000
        }
    },
    {
        type = "technology",
        name = MOD_NAME .. '/barrack',
        icons = {
            {
                icon = "__erm_terran__/graphics/entity/icons/advisor.png",
                icon_size = 64,
            },
            {
                icon = "__base__/graphics/icons/signal/signal_B.png",
                icon_size = 64,
                scale = 0.25,
                shift = {-20,-20}
            },
        },
        effects =
        {
            {
                type = "unlock-recipe",
                recipe = MOD_NAME .. '/barrack'
            },
        },
        prerequisites = {
            "military-2",
            "automation-2"
        },
        unit =
        {
            ingredients =
            {
                {"automation-science-pack", 1},
                {"logistic-science-pack", 1},
                {"military-science-pack", 1},
            },
            time = 30,
            count = 100
        },
    },
    {
        type = "technology",
        name = MOD_NAME .. '/factory',
        icons = {
            {
                icon = "__erm_terran__/graphics/entity/icons/advisor.png",
                icon_size = 64,
            },
            {
                icon = "__base__/graphics/icons/signal/signal_F.png",
                icon_size = 64,
                scale = 0.25,
                shift = {-20,-20}
            },
        },
        effects =
        {
            {
                type = "unlock-recipe",
                recipe = MOD_NAME .. '/factory'
            },
        },
        prerequisites = {
            "military-2",
            "low-density-structure",
        },
        unit =
        {
            ingredients =
            {
                {"automation-science-pack", 1},
                {"logistic-science-pack", 1},
                {"military-science-pack", 1},
                { "chemical-science-pack", 1 },
            },
            time = 45,
            count = 200
        },
    },
    {
        type = "technology",
        name = MOD_NAME .. '/starport',
        icons = {
            {
                icon = "__erm_terran__/graphics/entity/icons/advisor.png",
                icon_size = 64,
            },
            {
                icon = "__base__/graphics/icons/signal/signal_S.png",
                icon_size = 64,
                scale = 0.25,
                shift = {-20,-20}
            },
        },
        effects =
        {
            {
                type = "unlock-recipe",
                recipe = MOD_NAME .. '/starport'
            },
        },
        prerequisites = {
            "military-3",
            "low-density-structure",
        },
        unit =
        {
            ingredients =
            {
                {"automation-science-pack", 1},
                {"logistic-science-pack", 1},
                {"military-science-pack", 1},
                { "chemical-science-pack", 1 },
                { "utility-science-pack", 1 }
            },
            time = 60,
            count = 500
        },
    }

})
