---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 2/12/2021 8:20 PM
---

require('__erm_terran__/global')

local marine = 'marine'
local tank = 'tank'
local wraith = 'wraith'
local battlecruiser = 'battlecruiser'

data:extend({
    {
        type = "technology",
        name = MOD_NAME .. '/' .. marine .. '/mk-1',
        icon_size = 64,
        icon = "__erm_terran__/graphics/entity/icons/units/"..marine..".png",
        effects =
        {
            {
                type = "unlock-recipe",
                recipe = MOD_NAME .. '/' .. marine .. '/mk1'
            },
        },
        prerequisites = {"military-2", "heavy-armor"},
        unit =
        {
            ingredients =
            {
                {"automation-science-pack", 1},
                {"logistic-science-pack", 1},
                {"military-science-pack", 1},
            },
            time = 30,
            count = 250
        },
    },
    {
        type = "technology",
        name = MOD_NAME .. '/' .. marine .. '/mk-2',
        icon_size = 64,
        icon = "__erm_terran__/graphics/entity/icons/units/"..marine..".png",
        effects =
        {
            {
                type = "unlock-recipe",
                recipe = MOD_NAME .. '/' .. marine .. '/mk2'
            },
        },
        prerequisites = {"military-3","modular-armor", MOD_NAME .. '/' .. marine .. '/mk-1'},
        unit =
        {
            ingredients =
            {
                {"automation-science-pack", 1},
                {"logistic-science-pack", 1},
                {"chemical-science-pack", 1},
                {"military-science-pack", 1},
            },
            time = 60,
            count = 500
        },
    },
    {
        type = "technology",
        name = MOD_NAME .. '/' .. marine .. '/mk-3',
        icon_size = 64,
        icon = "__erm_terran__/graphics/entity/icons/units/"..marine..".png",
        effects =
        {
            {
                type = "unlock-recipe",
                recipe = MOD_NAME .. '/' .. marine .. '/mk3'
            },
        },
        prerequisites = {"military-4","modular-armor",'uranium-ammo', MOD_NAME .. '/' .. marine .. '/mk-2'},
        unit =
        {
            ingredients =
            {
                {"automation-science-pack", 1},
                {"logistic-science-pack", 1},
                {"chemical-science-pack", 1},
                {"military-science-pack", 1},
                {"utility-science-pack", 1}
            },
            time = 60,
            count = 1000
        },
    },
    {
        type = "technology",
        name = MOD_NAME .. '/' .. tank,
        icon_size = 64,
        icon = "__erm_terran__/graphics/entity/icons/units/"..tank..".png",
        effects =
        {
            {
                type = "unlock-recipe",
                recipe = MOD_NAME .. '/' .. tank
            },
        },
        prerequisites = {
            "military-4", "tank", "rocket-control-unit",
            "rocket-fuel", "low-density-structure", MOD_NAME .. '/' .. marine .. '/mk-3'
        },
        unit =
        {
            ingredients =
            {
                {"automation-science-pack", 1},
                {"logistic-science-pack", 1},
                {"chemical-science-pack", 1},
                {"military-science-pack", 1},
                {"utility-science-pack", 1}
            },
            time = 60,
            count = 2000
        },
    },
    {
        type = "technology",
        name = MOD_NAME .. '/' .. wraith,
        icon_size = 64,
        icon = "__erm_terran__/graphics/entity/icons/units/"..wraith..".png",
        effects =
        {
            {
                type = "unlock-recipe",
                recipe = MOD_NAME .. '/' .. wraith
            },
        },
        prerequisites = {
            "military-4", "low-density-structure",
            "rocket-control-unit",  MOD_NAME .. '/' .. marine .. '/mk-3',
            "explosive-rocketry", "rocket-fuel"
        },
        unit =
        {
            ingredients =
            {
                {"automation-science-pack", 1},
                {"logistic-science-pack", 1},
                {"chemical-science-pack", 1},
                {"military-science-pack", 1},
                {"utility-science-pack", 1}
            },
            time = 60,
            count = 2000
        },
    },
    {
        type = "technology",
        name = MOD_NAME .. '/' .. battlecruiser,
        icon_size = 64,
        icon = "__erm_terran__/graphics/entity/icons/units/"..battlecruiser..".png",
        effects =
        {
            {
                type = "unlock-recipe",
                recipe = MOD_NAME .. '/' .. battlecruiser
            },
        },
        prerequisites = {
            "military-4", "nuclear-power",
            "low-density-structure",  MOD_NAME .. '/' .. marine .. '/mk-3',
            "rocket-control-unit", "laser-turret"
        },
        unit =
        {
            ingredients =
            {
                {"automation-science-pack", 1},
                {"logistic-science-pack", 1},
                {"chemical-science-pack", 1},
                {"military-science-pack", 1},
                {"utility-science-pack", 1}
            },
            time = 60,
            count = 4000
        },
    },
})
