---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 9/21/2023 9:08 PM
---
local version = require('__stdlib__/stdlib/vendor/version')
require('__erm_terran__/global')

if mods['Krastorio2'] and version(mods['Krastorio2']) >= version("1.2.0") then

    local marine_mk1 = data.raw['recipe'][MOD_NAME .. '/marine/mk1']
    local marine_mk2 = data.raw['recipe'][MOD_NAME .. '/marine/mk2']
    local marine_mk3 = data.raw['recipe'][MOD_NAME .. '/marine/mk3']
    local goliath = data.raw['recipe'][MOD_NAME .. '/goliath']


    if settings.startup['erm_terran-cheap-mode'].value then
        marine_mk1['ingredients'][3] = {"rifle-magazine", 10}
        marine_mk2['ingredients'][3] = {"armor-piercing-rifle-magazine", 15}
        marine_mk3['ingredients'][3] = {"uranium-rifle-magazine", 15}
        goliath['ingredients'][4] = {"uranium-rifle-magazine", 25}
    else
        marine_mk1['ingredients'][3] = {"rifle-magazine", 20}
        marine_mk2['ingredients'][3] = {"armor-piercing-rifle-magazine", 25}
        marine_mk3['ingredients'][3] = {"uranium-rifle-magazine", 25}
        goliath['ingredients'][4] = {"uranium-rifle-magazine", 50}
    end
end