---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 12/23/2020 8:27 PM
---

local CustomAttackHelper = require('__enemyracemanager__/lib/helper/custom_attack_helper')
local ERMConfig = require('__enemyracemanager__/lib/global_config')
require('__erm_terran__/global')

local CustomAttacks = CustomAttackHelper

CustomAttacks.add_nuke_to_queue = function(event)
    if event.source_entity and event.source_entity.valid and (event.target_entity or event.target_position) then
        log('Nuke Queue Added @ '..event.tick)
        local target_position = event.target_position
        if event.target_entity then
            target_position = event.target_entity.position
        end

        local targeter_id = rendering.draw_animation({
            animation = MOD_NAME .. '/nuclear_targeter',
            target = target_position,
            time_to_live = NUKE_WAIT_TIME,
            surface = event.source_entity.surface.index,
            render_layer = 'radius-visualization'
        })
        global.nuke_tracker[event.source_entity.unit_number] = {
            entity = event.source_entity,
            target_position = target_position,
            launch_tick = event.tick + NUKE_WAIT_TIME,
            targeter_id = targeter_id
        }
        global.nuke_tracker_total = global.nuke_tracker_total + 1
    end
end

CustomAttacks.cancel_nuke_from_queue = function(event)
    if event.source_entity.valid and global.nuke_tracker[event.source_entity.unit_number] then
        log('Nuke Queue Cancelled @ '..event.tick)
        local nuke_data = global.nuke_tracker[event.source_entity.unit_number]
        rendering.destroy(nuke_data.targeter_id)
        global.nuke_tracker[event.source_entity.unit_number] = nil
        global.nuke_tracker_total = global.nuke_tracker_total - 1
    end
end

CustomAttacks.spawn_nuke = function(event)
    if global.nuke_tracker_total == 0 then
        return
    end

    for index, nuke_data in pairs(global.nuke_tracker) do
        if nuke_data.entity.valid and event.tick >= nuke_data.launch_tick then
            local surface = nuke_data.entity.surface
            local spawn_position = nuke_data.entity.position
            spawn_position.y = spawn_position.y - 32;
            rendering.destroy(nuke_data.targeter_id)
            global.nuke_tracker[index] = nil
            global.nuke_tracker_total = global.nuke_tracker_total - 1

            surface.create_entity {
                name = MOD_NAME .. "/atomic-bomb",
                --target = nuke_data.target_position,
                target = {
                    x = nuke_data.target_position.x + math.random(-4,4),
                    y = nuke_data.target_position.y + math.random(-4,4)
                },
                source = nuke_data.entity,
                position = spawn_position,
                direction = defines.direction.south,
                force = nuke_data.entity.force,
                speed = 0.25,
            }

        elseif nuke_data.entity.valid == false and event.tick > nuke_data.launch_tick then
            rendering.destroy(nuke_data.targeter_id)
            global.nuke_tracker[index] = nil
            global.nuke_tracker_total = global.nuke_tracker_total - 1
        end
    end
end

return CustomAttacks