---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 2/8/2023 9:02 PM
---
local RemoteAPI = {}

function RemoteAPI.milestones_preset_addons()
    local preset = {
        ["erm_terran"] = {
            required_mods = {"erm_terran"},
            milestones = {
                {type="group", name="Terran Research"},
                {type="technology", name="erm_terran/marine/mk-1",  quantity=1},
                {type="technology", name="erm_terran/marine/mk-2",  quantity=1},
                {type="technology", name="erm_terran/marine/mk-3",  quantity=1},
                {type="technology", name="erm_terran/firebat/mk-1",  quantity=1},
                {type="technology", name="erm_terran/firebat/mk-2",  quantity=1},
                {type="technology", name="erm_terran/siege_tank/mk-1",  quantity=1},
                {type="technology", name="erm_terran/siege_tank/mk-2",  quantity=1},
                {type="technology", name="erm_terran/goliath",  quantity=1},
                {type="technology", name="erm_terran/wraith",  quantity=1},
                {type="technology", name="erm_terran/battlecruiser",  quantity=1},
            }
        },
    }

    return preset
end

return RemoteAPI
